### ISSUE TITLE
Google redirect_uri_mismatch due to redirect_routes that is not https

### ISSUE THREAD

**Issue by wehostadm** [knpuniversity/oauth2-client-bundle#315] opened 2021-06-03 14:16 UTC
Hi,

Google has changed its rules for Oauth2 redirect URI and we should now use https. 
I use Symfony 4 with your bundle and the configuration file is : 

```
# https://github.com/knpuniversity/oauth2-client-bundle#configuration
knpu_oauth2_client:
    clients:
        google:
            type: google
            client_id: '%google_client_id%'
            client_secret: '%google_client_secret%'
            redirect_route: connect_check_login
```

In the security controller, the route is defined like this : 
```
/**
     * @Route("/connect/check", schemes={"https"}, name="connect_check_login")
     */
    public function checkAction(Request $request)
    {
        // do nothing, it's catched by the guard authenticator
    }
```

However, it continues to generates an http route : http://localhost/connect/check

The result is a 400 error code form Google : redirect_uri_mismatch 

How can I force to generate **https://localhost/connect/check** with https protocol ? 

Thanks a lot

**Comment by jbelien** [comment] 2021-08-15 15:29
I have the same issue with a [custom provider](https://github.com/jbelien/oauth2-openstreetmap) that also requires HTTPS (if it's not `localhost`).

Issue is happening on Heroku: https://osm-welcome-tool.herokuapp.com/

Any idea how to fix this (or force HTTPS for `redirect_uri`) ?
Thanks.

**Comment by jbelien** [comment] 2021-08-18 16:54
I could fix this issue following the trusted proxies configuration : https://symfony.com/doc/current/deployment/proxies.html#but-what-if-the-ip-of-my-reverse-proxy-changes-constantly

I hope it will help you too.

**Comment by orangevinz** [comment] 2021-09-01 13:22
You can use a tool like [Ngrok](https://ngrok.com/) to make a "tunnel" and expose your localhost on internet
`@Route("/connect/google/check", name="connect_google_check", host="xxx-xxx-xxx-xxxx.ngrok.io", schemes={"https"})`

**Comment by DonCallisto** [comment] 2021-10-06 08:05
This issue isn't related to the bundle, am I wrong? If not, please close this issue. Thanks.

**Comment by DonCallisto** [comment] 2021-10-06 12:18
Ok. Can you close this, please?

**Comment by julbrs** [comment] 2021-10-06 12:21
> Ok. Can you close this, please?

I think that only the original author (@wehostadm) or mainteners of the bundle can close the case,

**Comment by DonCallisto** [comment] 2021-10-06 12:22
Yeah sorry, thought it was you.

**Comment by lordjancso** [comment] 2023-09-08 15:06
It looks like this issue is still not solved fully.
How can I force the bundle to redirect a https url?
For some clients like facebook the https redirect url is mandatory.
Thank you for the help!

**Comment by weaverryan** [comment] 2023-09-11 14:09
Closing - as mentioned, this is likely a misconfig of your trusted proxies config.

put simply: if your user is already on https on your site, symfony will generate https urls. If your user is on https and symfony is NOT generating https urls, then this is because symfony thinks the user is on http, and that’s caused by symfony not trusting the “X-Forwarded-Proto” header sent by a reverse proxy somewhere in your stack.

**Closed by weaverryan** 2023-09-11 14:09 UTC
